site: LPS
title: Libros, películas y series
description: >-
  En esta página vas a encontrar mis reseñas sobre libros, películas y series.
googlewebfonts: Fira+Code:wght@400;500;700
lang: en-US
timezone: America/Argentina/Buenos_Aires
repo: https://github.com/yeite/lps # site repo [optional]
data-theme: dark # default theme "dark" | "light"

author:
  name: Matias
  bio: Microreseñas sobre libros, películas y series.
  username: yeite # general username
  github:  # github username
  twitter: matiasrz_ # twitter username
  email: your-email@email.com # email adress

# URL settings
url: "https://yeite.github.io" # Domain Name of host. [username].github.io for github pages
baseurl: "/lps" # sub folder for jekyll site. only if jekyll site not in root of host. leave blank if not wishd. always add / in front.
permalink: pretty


# Homepage limit posts
number_of_posts: 5


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
  - jekyll-admin

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false


